### ISSUE TITLE
Fetche price

### ISSUE THREAD

**Issue by bkaritasjensen** [rts-cmk/hifi-corner-api#10]
Hej Brian 
Er det muligt du kan lave API til price også?

**Comment by BrianEmilius** [comment]
@bkaritasjensen Jo det kan sagtens lade sig gøre. Vil du lige beskrive lidt nærmere hvad du tænker? Du må meget gerne også komme med et eksempel på hvordan et API-kald kunne se ud.

**Comment by bkaritasjensen** [comment]
Ligesom når vi henter products fra API, således: https://hifi-corner.herokuapp.com/api/v1/products

Så skal det være med price i stedet for. Så jeg kan lave filter søgning i prisen (f.eks. produkter fra 1000-2000 kr. vises) på products siden.

**Comment by BrianEmilius** [comment]
Noget i retning af dette? 
`https://hifi-corner.herokuapp.com/api/v1/products?minPrice=1000&maxPrice=3000`

**Comment by BrianEmilius** [comment]
Denne feature er blevet implementeret.
