### ISSUE TITLE
Ikke alle produkter er tilgængelig ingennem "Single product (by SKU)"

### ISSUE THREAD

**Issue by HenrikDK2** [rts-cmk/hifi-corner-api#4]
Jeg kan kalde på data med sku værdi 14, 12, men ikke 18 og 20.
Alle produkterne vises i https://hifi-corner.herokuapp.com/api/v1/products"

```javascript
  fetch(`https://hifi-corner.herokuapp.com/api/v1/products/0014`, {
        "method": "GET"
    })
        .then(response => response.json())
        .then(data => {
            console.log(data)
        }).catch(err => console.error(err));
}
```

**Comment by BrianEmilius** [comment]
Jeg lukker bare dette issue - vi blev vist enige om at "fejlen" skyldtes t API var lidt sløvt da du arbejdede med det.
